(vl-load-com)

(defun _pt->2d (p)
  (list (car p) (cadr p))
)

(defun _make-safearray (lst / sa)
  (setq sa (vlax-make-safearray vlax-vbDouble (cons 0 (1- (length lst)))))
  (vlax-safearray-fill sa lst)
  sa
)

(defun _copy-entity (e / obj)
  (setq obj (vlax-ename->vla-object e))
  (vla-copy obj)
)

(defun _get-lowest-point (e / obj end i p minpt minz)
  (setq obj (vlax-ename->vla-object e))
  (setq end (fix (vlax-curve-getendparam e)))
  (setq i 0)
  (setq minpt nil minz nil)
  (while (<= i end)
    (setq p (vlax-curve-getpointatparam e i))
    (if (or (null minz) (< (caddr p) minz))
      (progn
        (setq minz (caddr p))
        (setq minpt p)
      )
    )
    (setq i (1+ i))
  )
  minpt
)

(defun _region-area-from-poly (e / obj reg sa arr area)
  (setq obj (vlax-ename->vla-object e))
  (setq reg (vlax-invoke (vla-get-ModelSpace (vla-get-ActiveDocument (vlax-get-acad-object)))
                         'AddRegion
                         (vlax-make-variant
                           (vlax-safearray-fill
                             (vlax-make-safearray vlax-vbObject (cons 0 0))
                             (list obj)
                           )
                         )
               )
  )
  (setq arr (vlax-variant-value (vla-get-Area (vlax-invoke reg 'Item 0))))
  (setq area (vlax-get (vlax-invoke reg 'Item 0) 'Area))
  (vla-delete (vlax-invoke reg 'Item 0))
  area
)

(defun _make-cut-poly (poly y / coords newpts var obj pline)
  (setq obj (vlax-ename->vla-object poly))
  (setq coords '())
  (setq newpts nil)
  (setq var (vlax-get obj 'Coordinates))
  (setq coords (vlax-safearray->list (vlax-variant-value var)))
  (setq newpts
    (mapcar
      (function (lambda (p) (list (car p) y)))
      (mapcar 'list (vl-list->list coords))
    )
  )
)

(defun c:Q100LEVEL (/ e q100 lowpt lowz h testarea doc ms p1 p2 ln obj ss area tol done)
  (setq e (car (entsel "\nVyber uzavretú polyline: ")))
  (if (and e (= (cdr (assoc 0 (entget e))) "LWPOLYLINE"))
    (progn
      (setq q100 (getreal "\nZadaj hodnotu Q100: "))
      (setq lowpt (_get-lowest-point e))
      (setq lowz (caddr lowpt))
      (setq h lowz)
      (setq tol 1e-6)
      (setq done nil)
      (while (not done)
        (setq p1 (list (- (car lowpt) 1000.0) h (caddr lowpt)))
        (setq p2 (list (+ (car lowpt) 1000.0) h (caddr lowpt)))
        (command "_.LINE" p1 p2 "")
        (setq ln (entlast))
        (command "_.TRIM" e "" ln "")
        (if (and ln (entget ln))
          (progn
            (setq area (vlax-curve-getArea e))
            (if (> area q100)
              (setq done T)
              (progn
                (entdel ln)
                (setq h (+ h 0.01))
              )
            )
          )
          (setq done T)
        )
      )
      (setq Hhladina (- h lowz))
      (princ (strcat "\nDefinitívna hladina: " (rtos h 2 3)))
      (princ (strcat "\nHhladina: " (rtos Hhladina 2 3)))
    )
    (princ "\nVybraný objekt nie je LWPOLYLINE.")
  )
  (princ)
)